#pragma once
#include <windows.h>

enum Color
{
	BLACK,
	RED               = FOREGROUND_RED,
	GREEN             = FOREGROUND_GREEN,
	BLUE              = FOREGROUND_BLUE,
	YELLOW            = RED     | GREEN,
	CYAN              = BLUE    | GREEN,
	MAGENTA           = RED     | BLUE,
	GRAY              = RED     | GREEN | BLUE,
	LIGHT_RED         = RED     | FOREGROUND_INTENSITY,
	LIGHT_GREEN       = GREEN   | FOREGROUND_INTENSITY,
	LIGHT_BLUE        = BLUE    | FOREGROUND_INTENSITY,
	LIGHT_YELLOW      = YELLOW  | FOREGROUND_INTENSITY,
	LIGHT_CYAN        = CYAN    | FOREGROUND_INTENSITY,
	PINK              = MAGENTA | FOREGROUND_INTENSITY,
	WHITE             = GRAY    | FOREGROUND_INTENSITY,
	BACK_BLACK        = BLACK,
	BACK_RED          = BACKGROUND_RED,
	BACK_GREEN        = BACKGROUND_GREEN,
	BACK_BLUE         = BACKGROUND_BLUE,
	BACK_YELLOW       = BACK_RED     | BACK_GREEN,
	BACK_CYAN         = BACK_BLUE    | BACK_GREEN,
	BACK_MAGENTA      = BACK_RED     | BACK_BLUE,
	BACK_GRAY         = BACK_RED     | BACK_BLUE | BACK_GREEN,
	BACK_LIGHT_RED    = BACK_RED     | FOREGROUND_INTENSITY,
	BACK_LIGHT_GREEN  = BACK_GREEN   | FOREGROUND_INTENSITY,
	BACK_LIGHT_BLUE   = BACK_BLUE    | FOREGROUND_INTENSITY,
	BACK_LIGHT_YELLOW = BACK_YELLOW  | FOREGROUND_INTENSITY,
	BACK_LIGHT_CYAN   = BACK_CYAN    | FOREGROUND_INTENSITY,
	BACK_PINK         = BACK_MAGENTA | FOREGROUND_INTENSITY,
	BACK_WHITE        = BACK_GRAY    | FOREGROUND_INTENSITY
};
